on:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  workflow_dispatch:

name: MSRV check

jobs:
  msrv_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - name: Download cargo-msrv
        run: cargo install cargo-msrv
      - name: Check MSRV
        run: cargo msrv verify -- cargo check --all-features
