on:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  workflow_dispatch:

name: Cargo fmt

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - name: Check format
        run: cargo fmt --all -- --check
