on:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  workflow_dispatch:

name: Clippy check

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - name: Check with clippy
        run: cargo clippy --all-features
